services:
  web:
    build: .
    command: uvicorn delivery.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - minio

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${MINIO_ACCESS_KEY}
    volumes:
      - minio_data:/data
    extra_hosts:
      - "minio:host-gateway"

  celery_worker:
    build: .
    command: celery -A infrastructure.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  celery_beat:
    build: .
    command: celery -A infrastructure.celery_app beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  minio_data:
